_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.16
            "5": 0.18.3
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 512
dataset:
    value: GTSRB
gradient_accumulation_steps:
    value: 1
label_smoothing:
    value: 0.1
learning_rate:
    value: 5e-05
model:
    value: CLIP Supervised Fine-Tuning with Dormant Neuron Monitoring
num_epochs:
    value: 6
project:
    value: vitb32-gtsrb-dormant-neurons-seeds
seed:
    value: 52
thresholds:
    value:
        - 0.01
train_data_path:
    value: /users/zliu328/continual_learning/data/gtsrb/GTSRB/Training
val_annotations_file:
    value: /users/zliu328/continual_learning/data/gtsrb/GT-final_test.csv
val_img_dir:
    value: /users/zliu328/continual_learning/data/gtsrb/GTSRB/Final_Test/Images
weight_decay:
    value: 0.0001
